# Generated by Django 5.2.7 on 2025-11-04 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('tipo_trabajo', models.CharField(choices=[('ART', 'Artículo Científico'), ('TES_G', 'Tesis de Grado'), ('TES_P', 'Tesis de Posgrado')], default='ART', max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.CharField(choices=[('APR', 'Aprobar'), ('RECH', 'Rechazar'), ('RMEN', 'Revisión Menor'), ('RMAY', 'Revisión Mayor')], max_length=4)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
                ('revisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='solicitudes_app.solicitud')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
    ]
